dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // 안전한 QueryDSL 버전 (OpenFeign 포크 사용)
    implementation 'io.github.openfeign.querydsl:querydsl-jpa:7.1'
    annotationProcessor 'io.github.openfeign.querydsl:querydsl-apt:7.1:jpa'
}

jar { enabled = true }
bootJar { enabled = false }
